apiVersion: v1
kind: Namespace
metadata:
  name: workerpod
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fs-static-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      # node stage secret name
      name: csi-rbd-secret
      # node stage secret namespace where above secret is created
      namespace: ceph-csi-rbd
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "78be666a-2ee8-425a-81d4-c938372905d4"
      "pool": "kube"
      "staticVolume": "true"
      "imageFeatures": "layering"
      #mounter: rbd-nbd
    # volumeHandle should be same as rbd image name
    volumeHandle: deluge-config
  persistentVolumeReclaimPolicy: Retain
  # The volumeMode can be either `Filesystem` or `Block` if you are creating Filesystem PVC it should be `Filesystem`, if you are creating Block PV you need to change it to `Block`
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-pers
  namespace: workerpod
spec:
  volumeName: fs-static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: workerpod
  labels:
    app.kubernetes.io/name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:latest
    volumeMounts:
    - name: ceph
      mountPath: "/ceph"
  volumes:
  - name: ceph
    persistentVolumeClaim:
      claimName: ceph-pers
  command: ["tail"]
  args: ["-f", "/dev/null"]
