apiVersion: v1
kind: Namespace
metadata:
  name: hass
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hass
  namespace: hass
data:
  scripts.yaml: |
  scenes.yaml: |
  automations.yaml: |
  configuration.yaml: |-
    # Loads default set of integrations. Do not remove.
    default_config:
    
    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes
    
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
    homekit:
      advertise_ip: "192.168.10.56"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hass-config
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      # node stage secret name
      name: csi-rbd-secret
      # node stage secret namespace where above secret is created
      namespace: ceph-csi-rbd
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "78be666a-2ee8-425a-81d4-c938372905d4"
      "pool": "kube"
      "staticVolume": "true"
      "imageFeatures": "layering"
      #mounter: rbd-nbd
    # volumeHandle should be same as rbd image name
    volumeHandle: hass-config
  persistentVolumeReclaimPolicy: Retain
  # The volumeMode can be either `Filesystem` or `Block` if you are creating Filesystem PVC it should be `Filesystem`, if you are creating Block PV you need to change it to `Block`
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-config-claim
  namespace: hass
spec:
  volumeName: hass-config
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hass
  labels:
    app: hass
    pod-security.kubernetes.io/enforce: privileged
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hass
  template:
    metadata:
      labels:
        app: hass
    spec:
      hostNetwork: true
      containers:
      - name: hass
        image: homeassistant/home-assistant:2025.4.1
        ports:
        - containerPort: 8123
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /config/configuration.yaml
            subPath: configuration.yaml
            name: configmap-file
          - mountPath: /config/automations.yaml
            subPath: automations.yaml
            name: configmap-file
          - mountPath: /config/scenes.yaml
            subPath: scenes.yaml
            name: configmap-file
          - mountPath: /config/scripts.yaml
            subPath: scripts.yaml
            name: configmap-file
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: hass-config-claim
      - name: configmap-file
        configMap:
          name: hass
---
kind: Service
apiVersion: v1
metadata:
  name: hass
  namespace: hass
spec:
  selector:
    app: hass
  ports:   
    - name: hass-8123
      protocol: TCP
      port: 8123
