apiVersion: v1
kind: Namespace
metadata:
  name: downloaders
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/volume1/kube/config/deluge/"
    server: "192.168.10.51"
    readOnly: false
---
apiVersion: v1
kind: Pod
metadata:
  name: deluge
spec:
  containers:
  - name: deluge
    image: linuxserver/deluge:2.1.1
    ports:
    - containerPort: 58846
    - containerPort: 58946
    - containerPort: 8112
    env:
    - name: PGID
      value: "100"
    - name: PUID
      value: "1036"
    - name: TZ
      value: "Europe/Rome"
