apiVersion: v1
kind: Namespace
metadata:
  name: downloaders
---
apiVersion: v1
kind: Pod
metadata:
  name: deluge
spec:
  containers:
  - name: deluge
    image: linuxserver/deluge:2.1.1
    ports:
    - containerPort: 58846
    - containerPort: 58946
    - containerPort: 8112
    env:
    - name: PGID
      value: 100
    - name: PUID
      value: 1036
    - name: TZ
      value: "Europe/Rome"
