apiVersion: v1
kind: Namespace
metadata:
  name: downloaders
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-config
  namespace: downloaders
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/volume1/kube/config/deluge/"
    server: "192.168.10.51"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-config-claim
  namespace: downloaders
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: deluge
  labels:
    app.kubernetes.io/name: deluge
spec:
  containers:
  - name: deluge
    image: linuxserver/deluge:2.1.1
    ports:
    - containerPort: 58846
    - containerPort: 58946
    - containerPort: 8112
    env:
    - name: PGID
      value: "100"
    - name: PUID
      value: "1036"
    - name: TZ
      value: "Europe/Rome"
    volumeMounts:
    - name: config
      mountPath: "/config"
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: deluge-config-claim
---
kind: Service
apiVersion: v1
metadata:
  name: deluge
  namespace: downloaders
spec:
  selector:
    app.kubernetes.io/name: deluge
  ports:   
    - name: deluge-8112
      protocol: TCP
      port: 8112
