apiVersion: v1
kind: Namespace
metadata:
  name: nas  # create namespace nas
---
kind: Service
apiVersion: v1
metadata:
  name: nas-service-v4 
  namespace: nas
spec:
  ipFamilies:
  - IPv4
  ports:
    - name: nas-5000   
      protocol: TCP 
      port: 5000       
    - name: nas-5001   
      protocol: TCP
      port: 5001       
spec:
  type: ExternalName
  externalName: 192.168.10.51 # ip of external website of dns name of the external website
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas-ingress
  namespace: nas
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # Remark this entry if you only have a HTTP port connection to external webserver
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  rules:
  - host: home.danmor.eu 
    http:
      paths:
      - path: /
        pathType: Prefix  # pathType no longer has a default value in v1; "Exact", "Prefix", or "ImplementationSpecific" must be specified
        backend:
          service:
            name: nas-service-v4 # make sure this is same service name as in the service yaml
            port:
              number: 5001 
  tls: # < placing a host in the TLS config will indicate a cert should be created
  - hosts:
    -  home.danmor.eu
    secretName: home.danmor.eu-tls # < cert-manager will store the created certificate in this secret.
