apiVersion: v1
kind: Namespace
metadata:
  name: rp-ingress
---
kind: Service
apiVersion: v1
metadata:
  name: synology
  namespace: rp-ingress  
spec:
  type: ExternalName
  externalName: 192.168.10.51
---
kind: Service
apiVersion: v1
metadata:
  name: hass
  namespace: rp-ingress  
spec:
  type: ExternalName
  externalName: 192.168.10.55
---
kind: Service
apiVersion: v1
metadata:
  name: unifi
  namespace: rp-ingress  
spec:
  type: ExternalName
  externalName: 192.168.10.1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-ingress
  namespace: rp-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # Remark this entry if you only have a HTTP port connection to external webserver
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: home.danmor.eu 
    http:
      paths:
      - path: /
        pathType: Prefix  # pathType no longer has a default value in v1; "Exact", "Prefix", or "ImplementationSpecific" must be specified
        backend:
          service:
            name: synology # make sure this is same service name as in the service yaml
            port:
              number: 5001 
  tls:
  - hosts:
    -  home.danmor.eu
    secretName: home.danmor.eu-tls # < cert-manager will store the created certificate in this secret.
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deluge-ingress
  namespace: rp-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";
spec:
  ingressClassName: nginx
  rules:
  - host: deluge.danmor.eu 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: synology
            port:
              number: 8112
  tls:
  - hosts:
    -  deluge.danmor.eu
    secretName: deluge.danmor.eu-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drive-ingress
  namespace: rp-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: drive.danmor.eu 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: synology
            port:
              number: 443
  tls:
  - hosts:
    -  drive.danmor.eu
    secretName: drive.danmor.eu-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foundry-ingress
  namespace: rp-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";
spec:
  ingressClassName: nginx
  rules:
  - host: foundry.danmor.eu 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: synology
            port:
              number: 30000
  tls:
  - hosts:
    -  foundry.danmor.eu
    secretName: foundry.danmor.eu-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass-ingress
  namespace: rp-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: hass.danmor.eu 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hass
            port:
              number: 8123
  tls:
  - hosts:
    -  hass.danmor.eu
    secretName: hass.danmor.eu-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-ingress
  namespace: rp-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: sonarr.danmor.eu 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: synology
            port:
              number: 8989
  tls:
  - hosts:
    -  sonarr.danmor.eu
    secretName: sonarr.danmor.eu-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi-ingress
  namespace: rp-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: unifi.danmor.eu 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unifi
            port:
              number: 443
  tls:
  - hosts:
    -  unifi.danmor.eu
    secretName: unifi.danmor.eu-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifids-ingress
  namespace: rp-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: unifids.danmor.eu 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: synology
            port:
              number: 8443
  tls:
  - hosts:
    -  unifids.danmor.eu
    secretName: unifids.danmor.eu-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
    - host: argocd.danmor.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
